server:
  port: 3344
spring:
  application:
    # 注册进eureka服务器的微服务名
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          # github上面git仓库的名字
          uri: https://github.com/chenzejie-alt/springcloud-config.git
          # 仓库的名字，搜索目录
          search-paths:
            - springcloud-config
          force-pull: true
          username: chenzejie-alt
          password: liudu19990810.
          timeout: 10000
      # 读取分支
      label: master

# 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka