server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
  # 表示是否将自己注册进EurekaServer，默认为true，我们是服务提供者
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版，多个微服务提供者
  instance:
    instance-id: payment8001 # 修改主机名称
    # 访问信息有ip提示，访问路径可以显示ip地址
    prefer-ip-address: true
#    # 设置eureka客户端向服务端发送心跳的时间间隔，单位是秒（默认是30秒）
#    lease-renewal-interval-in-seconds: 1
#    # eureka服务端在收到最后一次心跳后等待时间上限，单位为秒，（默认是90秒），超时的话服务就会被剔除
#    lease-expiration-duration-in-seconds: 2